package com.meida.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTbOrder<M extends BaseTbOrder<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setNumber(String number) {
		set("number", number);
	}

	public String getNumber() {
		return get("number");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setAcceptUser(Long acceptUser) {
		set("acceptUser", acceptUser);
	}

	public Long getAcceptUser() {
		return get("acceptUser");
	}

	public void setAcceptTime(Long acceptTime) {
		set("acceptTime", acceptTime);
	}

	public Long getAcceptTime() {
		return get("acceptTime");
	}

	public void setTransitUser(Long transitUser) {
		set("transitUser", transitUser);
	}

	public Long getTransitUser() {
		return get("transitUser");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return get("remark");
	}

	public void setTotalWarehouse(Integer totalWarehouse) {
		set("totalWarehouse", totalWarehouse);
	}

	public Integer getTotalWarehouse() {
		return get("totalWarehouse");
	}

	public void setWaitInWarehouse(Integer waitInWarehouse) {
		set("waitInWarehouse", waitInWarehouse);
	}

	public Integer getWaitInWarehouse() {
		return get("waitInWarehouse");
	}

	public void setWaitExWarehouse(Integer waitExWarehouse) {
		set("waitExWarehouse", waitExWarehouse);
	}

	public Integer getWaitExWarehouse() {
		return get("waitExWarehouse");
	}

	public void setExWarehouse(Integer exWarehouse) {
		set("exWarehouse", exWarehouse);
	}

	public Integer getExWarehouse() {
		return get("exWarehouse");
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		set("deleteFlag", deleteFlag);
	}

	public Boolean getDeleteFlag() {
		return get("deleteFlag");
	}

	public void setOwnerId(Long ownerId) {
		set("ownerId", ownerId);
	}

	public Long getOwnerId() {
		return get("ownerId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setCreater(Long creater) {
		set("creater", creater);
	}

	public Long getCreater() {
		return get("creater");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setUpdater(Long updater) {
		set("updater", updater);
	}

	public Long getUpdater() {
		return get("updater");
	}

}
