package com.meida.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReceiver<M extends BaseReceiver<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setMobile(String mobile) {
		set("mobile", mobile);
	}

	public String getMobile() {
		return get("mobile");
	}

	public void setAddress(String address) {
		set("address", address);
	}

	public String getAddress() {
		return get("address");
	}

	public void setOriginalId(Long originalId) {
		set("originalId", originalId);
	}

	public Long getOriginalId() {
		return get("originalId");
	}

	public void setOriginalNumber(String originalNumber) {
		set("originalNumber", originalNumber);
	}

	public String getOriginalNumber() {
		return get("originalNumber");
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		set("deleteFlag", deleteFlag);
	}

	public Boolean getDeleteFlag() {
		return get("deleteFlag");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setCreater(Long creater) {
		set("creater", creater);
	}

	public Long getCreater() {
		return get("creater");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setUpdater(Long updater) {
		set("updater", updater);
	}

	public Long getUpdater() {
		return get("updater");
	}

}
