package com.meida.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTransitLogistic<M extends BaseTransitLogistic<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setNumber(String number) {
		set("number", number);
	}

	public String getNumber() {
		return get("number");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setContactInfo(String contactInfo) {
		set("contactInfo", contactInfo);
	}

	public String getContactInfo() {
		return get("contactInfo");
	}

	public void setWeight(java.math.BigDecimal weight) {
		set("weight", weight);
	}

	public java.math.BigDecimal getWeight() {
		return get("weight");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return get("remark");
	}

	public void setOrderId(Long orderId) {
		set("orderId", orderId);
	}

	public Long getOrderId() {
		return get("orderId");
	}

	public void setOriginalId(Long originalId) {
		set("originalId", originalId);
	}

	public Long getOriginalId() {
		return get("originalId");
	}

	public void setOriginalNumber(String originalNumber) {
		set("originalNumber", originalNumber);
	}

	public String getOriginalNumber() {
		return get("originalNumber");
	}

	public void setOriginalMobile(String originalMobile) {
		set("originalMobile", originalMobile);
	}

	public String getOriginalMobile() {
		return get("originalMobile");
	}

	public void setSendTime(Long sendTime) {
		set("sendTime", sendTime);
	}

	public Long getSendTime() {
		return get("sendTime");
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		set("deleteFlag", deleteFlag);
	}

	public Boolean getDeleteFlag() {
		return get("deleteFlag");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setCreater(Long creater) {
		set("creater", creater);
	}

	public Long getCreater() {
		return get("creater");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setUpdater(Long updater) {
		set("updater", updater);
	}

	public Long getUpdater() {
		return get("updater");
	}

}
