package com.meida.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setPath(String path) {
		set("path", path);
	}

	public String getPath() {
		return get("path");
	}

	public void setParentId(Long parentId) {
		set("parentId", parentId);
	}

	public Long getParentId() {
		return get("parentId");
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		set("deleteFlag", deleteFlag);
	}

	public Boolean getDeleteFlag() {
		return get("deleteFlag");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setCreater(Long creater) {
		set("creater", creater);
	}

	public Long getCreater() {
		return get("creater");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setUpdater(Long updater) {
		set("updater", updater);
	}

	public Long getUpdater() {
		return get("updater");
	}

	public void setClassName(String className) {
		set("className", className);
	}

	public String getClassName() {
		return get("className");
	}

}
